export const wizardEmojis = [
  { emoji_type: "heart_eyes", type: "gif" },
  { emoji_type: "umbrella", type: "gif" },
  { emoji_type: "lfg", type: "gif" },
  { emoji_type: "sigh", type: "gif" },
  { emoji_type: "tea_cup", type: "png" },
  { emoji_type: "smiley_face", type: "png" },
  { emoji_type: "sleeping", type: "png" },
  { emoji_type: "tears_of_joy", type: "png" },
  { emoji_type: "side_eye", type: "png" },
  { emoji_type: "crying", type: "png" },
  { emoji_type: "enraged_face", type: "png" },
  { emoji_type: "salute", type: "png" },
];

export const moonbirdEmojis = [
  { emoji_type: "raised_eyebrow", type: "png" },
  { emoji_type: "heart_eyes", type: "png" },
  { emoji_type: "nerd_face", type: "png" },
  { emoji_type: "face_with_sunglasses", type: "png" },
  { emoji_type: "enraged_face", type: "png" },
  { emoji_type: "teary_face", type: "png" },
  { emoji_type: "hushed_face", type: "png" },
  { emoji_type: "unamused_face", type: "png" },
  { emoji_type: "rolling_eyes_face", type: "png" },
  { emoji_type: "pensive_face", type: "png" },
  { emoji_type: "blow_kiss_face", type: "png" },
  { emoji_type: "halo_face", type: "png" },
  { emoji_type: "tears_of_joy", type: "png" },
  { emoji_type: "artist", type: "png" },
  { emoji_type: "programmer", type: "png" },
  { emoji_type: "tea_cup", type: "png" },
  { emoji_type: "crying", type: "png" },
  { emoji_type: "beer", type: "png" },
  { emoji_type: "love", type: "png" },
  { emoji_type: "french_fries", type: "png" },
  { emoji_type: "gaming", type: "png" },
  { emoji_type: "thumb_up", type: "png" },
  { emoji_type: "sleeping", type: "png" },
  { emoji_type: "waving", type: "png" },
  { emoji_type: "face_in_palm", type: "png" },
];
